version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dev-review-required'
      - 'dependencies'
    cooldown:
      default-days: 7
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dev-review-required'
      - 'dependencies'
    cooldown:
      default-days: 7
