repos:
-   repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
    - id: black
      language_version: python3.12
-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
    - id: mypy