name: Bump version and release
on:
  workflow_dispatch:
  push:
    # branches:
    #   - main
concurrency:
  group: release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.10'
      - name: Bump version and push tag
        uses: jasonamyers/github-bumpversion-action@v1.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     tags: true
      - name: Build binaries
        run: |
          python -m pip install --no-cache-dir --upgrade pip wheel twine build setuptools
          python -m build
          python -m twine check dist/*
      # - name: Upload to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}
